# Generated by Django 4.2.4 on 2023-08-14 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0002_customuser_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdetail',
            name='available_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slotdetail',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slotdetail',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='slotdetail',
            name='opening_hours',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='slotdetail',
            name='vehicle_type',
            field=models.CharField(choices=[('2_wheeler', '2 Wheeler'), ('4_wheeler', '4 Wheeler'), ('Truck', 'Truck'), ('Bus', 'Bus'), ('Heavy Vehicle', 'Heavy Vehicle')], default='2_wheeler', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epark_app.slotdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
