# Generated by Django 4.2.4 on 2023-08-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0003_slotdetail_available_slots_slotdetail_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
        migrations.AlterModelTable(
            name='slotbooking',
            table='SlotBooking',
        ),
        migrations.AlterModelTable(
            name='slotdetail',
            table='SlotDetail',
        ),
    ]
