# Generated by Django 4.2.4 on 2023-08-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0004_alter_location_table_alter_slotbooking_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
        migrations.AlterModelTable(
            name='slotbooking',
            table='slotbooking',
        ),
        migrations.AlterModelTable(
            name='slotdetail',
            table='slotdetail',
        ),
    ]
