# Generated by Django 4.2.4 on 2023-08-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0005_alter_customuser_table_alter_location_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
