# Generated by Django 4.2.4 on 2023-08-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0006_remove_location_latitude_remove_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdetail',
            name='address',
        ),
        migrations.AddField(
            model_name='slotdetail',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='epark_app.location'),
            preserve_default=False,
        ),
    ]
