# Generated by Django 4.2.4 on 2023-08-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0008_slotbooking_vehicle_number_slotbooking_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
