# Generated by Django 4.2.4 on 2023-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0010_alter_slotbooking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
