# Generated by Django 4.2.4 on 2023-08-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0015_remove_slotbooking_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='vehicle_type',
            field=models.CharField(choices=[('2_wheeler', '2 Wheeler'), ('4_wheeler', '4 Wheeler'), ('Truck', 'Truck'), ('Bus', 'Bus'), ('Heavy Vehicle', 'Heavy Vehicle')], default='2_wheeler', max_length=20),
        ),
    ]
