# Generated by Django 4.2.4 on 2023-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0016_slotbooking_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetail',
            name='slot_variants',
            field=models.ManyToManyField(blank=True, to='epark_app.slotdetailvariant'),
        ),
    ]
