# Generated by Django 4.2.4 on 2023-08-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0017_alter_slotdetail_slot_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='user',
        ),
    ]
