# Generated by Django 4.2.4 on 2023-08-27 02:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0019_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
