# Generated by Django 4.2.4 on 2023-08-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0020_location_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slotdetail',
            unique_together={('location', 'name')},
        ),
    ]
