# Generated by Django 4.2.4 on 2023-08-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0021_alter_slotdetail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotdetail',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
