# Generated by Django 4.2.4 on 2023-08-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0022_alter_slotdetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdetailvariant',
            name='is_slot_relese',
            field=models.BooleanField(default=False),
        ),
    ]
