# Generated by Django 4.2.4 on 2023-08-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0023_slotdetailvariant_is_slot_relese'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdetailvariant',
            name='is_slot_relese',
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='is_slot_relese',
            field=models.BooleanField(default=False),
        ),
    ]
