# Generated by Django 4.2.4 on 2023-08-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0024_remove_slotdetailvariant_is_slot_relese_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='is_bill_generated',
            field=models.BooleanField(default=False),
        ),
    ]
