# Generated by Django 4.2.4 on 2023-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0025_slotbooking_is_bill_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotdetailvariant',
            old_name='hourly_rate',
            new_name='daily_rate',
        ),
        migrations.AddField(
            model_name='slotdetailvariant',
            name='hourly_rate_12_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='slotdetailvariant',
            name='hourly_rate_1_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='slotdetailvariant',
            name='hourly_rate_3_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='slotdetailvariant',
            name='hourly_rate_6_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
