# Generated by Django 4.2.4 on 2023-08-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0026_rename_hourly_rate_slotdetailvariant_daily_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotdetail',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
