# Generated by Django 4.2.4 on 2023-08-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0027_remove_slotdetail_opening_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='is_slot_relese',
        ),
    ]
