# Generated by Django 4.2.4 on 2023-09-02 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0028_remove_slotbooking_is_slot_relese'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='closing_hours',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epark_app.location')),
            ],
            options={
                'unique_together': {('location', 'day_of_week')},
            },
        ),
    ]
