# Generated by Django 4.2.4 on 2023-09-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0029_location_closing_hours_openinghours'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='openinghours',
            table='openinghours',
        ),
    ]
