# Generated by Django 4.2.4 on 2023-09-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epark_app', '0031_alter_customuser_parking_lot_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_location',
            field=models.BooleanField(default=False),
        ),
    ]
